version: "3.5"

services:
  postgres_test:
    image: postgres:15-alpine
    volumes:
      - pg-data-test:/var/lib/postgresql/data
    env_file:
      - .env.test
    networks:
      - backend_test

  backend_test:
    build: .
    command: bash -c 'sleep 6 && npx jest'
    env_file:
      - .env.test
    depends_on:
      - postgres_test
      - backend_migrate_test
    networks:
      - backend_test

  backend_migrate_test:
    build: .
    command: bash -c 'sleep 5 && npx prisma migrate deploy'
    env_file:
      - .env.test
    depends_on:
      - postgres_test
    networks:
      - backend_test

networks:
  backend_test:


volumes:
  pg-data-test:
